### ISSUE TITLE
support for dynarec - on mips32 (without r2) devices 

### ISSUE THREAD

**Issue by Poligraf** [libretro/gpsp#138]
Device is a jz4760 which is a mips32 device.

Dynarec works perfectly on the jz4770 mips32r2.

On my unofficial fork for RA on the jz4760 I am getting "illegal instruction" error if I try to use the dynarec (tested on latest commit on 27/6/2021). This is as expected.

I understand that support for dynarec for non mips32r2  is currently a work in progress and not a priority for unofficial libretro builds, but I hope that this gets completed eventually. 

Thank you.

**Comment by davidgfnet** [comment]
Oh nice!
It's your lucky day: I added this (e0a31952) the other day. Is not 100% complete, we need to fix the palette conversion routines that still use such instructions.
I'm working on this for PS2 (which doesn't have any of those insts). I'd love to collaborate with you since the emu is not yet working on PS2 (and I'm not 100% sure why). 
Mind chiming in on Discord? We can chat and we can test some builds to figure out whether they work or not :)
Thanks!

**Comment by Poligraf** [comment]
issue is fixed as of 4/7/21
