### ISSUE TITLE
[VITA/WINDOWS] Silent Scope gives blue screen when arcade mode selected

### ISSUE THREAD

**Issue by 16mpx** [libretro/gpsp#140]
Hi,

Silent Scope (U) game gives blue screen and freezes when arcade mode selected from the menu. This happens for both Vita and Windows builds.

**Comment by davidgfnet** [comment]
Are you using the original BIOS or the built-in one?
Also mind pasting the ROM hash? Thanks!

**Comment by 16mpx** [comment]
Using the original BIOS.

Below is the ROM hash values calculated via https://www.romhacking.net/hash/

File SHA1 | 22D8D57AC4B274933ADB492FEE2B32BBC7B6E9BB
ROM SHA1 | 22D8D57AC4B274933ADB492FEE2B32BBC7B6E9BB
File MD5 | 164E42954FE047552701FF62836642AE
ROM MD5 | 164E42954FE047552701FF62836642AE
File CRC32 | C5CE1B2C
ROM CRC32 | C5CE1B2C

Additional info; game is playing fine with the gpsp core from the February/2021.

**Comment by davidgfnet** [comment]
I've fixed a couple of bugs in the open-bios-read path and that has fixed a few games (like Zelda). This game was also fixed from the looks of it (in Vita at least). On PC it works well for me.
Please test it using the latest version (otherwise the fix won't be there of course!) and reopen if still an issue. You should get the nightly build tonight for you to test.
