### ISSUE TITLE
Rom hacks crash

### ISSUE THREAD

**Issue by Carryingthebanner** [libretro/gpsp#177]
Any rom hacks crash unexpectedly on vita and PC when using speed up. Pokémon and Mega Man Battle Network 6 hacks tried.

**Comment by davidgfnet** [comment]
Can you please link any of the ROMs? We cannot test them unless we have them :)

**Comment by andymcca** [comment]
@davidgfnet no reply and no specific ROM hacks reported after 6 months since your reply, think this one is ok to close?

**Comment by Carryingthebanner** [comment]
Sorry there is a MegaMan Battle Network 6 Cybeast Gregar English translation rom hack that crashes.

**Comment by andymcca** [comment]
@Carryingthebanner thanks for the reply, how does it crash and what version of RetroArch / gpsp are you using?

Does this ROM hack work on actual hardware?  The problem with ROM hacks is that sometimes they rely on specific emulator behaviour or actual hardware quirks to work.  The latter being somewhat easier to figure out but in general they seem to be a pain to support especially when the problem turns out to be in the hack code itself.

**Comment by Carryingthebanner** [comment]
![image](https://github.com/libretro/gpsp/assets/113789485/8efad2c8-c5c0-4ddb-84b6-e5f737810eca)

I tried it on original hardware and it works. Not sure of the image answers the question of which version of gpsp though.

**Comment by davidgfnet** [comment]
If a rom makes the emulator crash you need to provide the rom for us to test. You can drop me an email for that.
