### ISSUE TITLE
Demikids crash when the fight start the game 

### ISSUE THREAD

**Issue by schmurtzm** [libretro/gpsp#181]
Demikids crash when the fight start the game (after the introduction).

https://user-images.githubusercontent.com/7110113/211165091-37c86502-1e60-421c-bea9-831e356ef1b7.mp4

It doesn't crash without dynarec but it freeze witht strange sounds.

Tested with last gPSP commit : 90170e33894ac8e3598a5660da62a18884d795f4 5 jan 2023
default parameter : dynarec ON + interframe blending OFF
platform armv7 + neon
also crashing on x86 in the same way (may be less often)

**Comment by andymcca** [comment]
Crashes at the same point on ARM32 on gpsp standalone, giving a 'Bad Jump' error.  Switching to Interpreter mode just before the crash will stop it crashing but will simply remain on a black screen (RetroArch still responsive).

**Comment by andymcca** [comment]
Fairly sure this is to do with IRQ handling and the game trying to do something weird at this point, just can't put my finger on what's happening though.  I need a better debugging setup!

**Comment by andymcca** [comment]
Does NOT happen on gpsp 0.9 standalone (played on PPSSPP)!

**Comment by andymcca** [comment]
Following some debugging I've managed to get it to a point on ARM32 Dynarec where it will no longer crash and the music/sound continues as normal, but the screen is blank (first battle).

ARM32 Dynarec differs significantly from MIPS, and it appears that this issue is being caused by the register store/restore routines possibly not providing enough coverage.  Next experiment will be to see if I can change these to be more in line with ARM64/MIPS and if this will solve the issue.

Interpreter seemingly does NOT work on any platform, including MIPS.  Same issue you describe above.

**Comment by davidgfnet** [comment]
Don't put the work for nothing I'd say. Savestates are cross platform so you can compare them. You can first prove that the dynarecs diverge an how/why. Then you find the fix. Just a suggestion ;)

**Comment by andymcca** [comment]
Thanks @davidgfnet - think I may focus on Interpreter mode first, as the crash happens in the same place there too on every platform.  By the way, I found this ancient blog from Exophase (original gpsp creator), mostly covering the ARM dynarec development - interesting read for background maybe?  https://gpsp-dev.blogspot.com/

**Comment by andymcca** [comment]
Update - working on the Interpreter.  Have raised new issue #193  I found whilst working on it but unfortunately fixing it doesn't fix this issue, which is now driving me mad, haha!

The problem appears to be when a CPU alert is detected and an interrupt is subsequently raised, which then changes the CPU mode.  This seems to be correct behaviour for this part of the game, but I can only assume that registers are being incorrectly set somehow (possibly the program counter) which then causes the problems described above.

Ultimately what I think I'll need to do is compare the subsequent instructions/registers against another emulator (e.g. mgba) at this point in the game and see where it's diverging.  MIPS core works ok, but ARM and Interpreter do not.

**Comment by andymcca** [comment]
OK @davidgfnet , here's one for you!

In DemiKids Light at pc = 0x080A05BE there are two Thumb BL low/high instructions one after the other (so 4 instructions in total).  

In Interpreter and ARM32 Dynarec, the first low/high seems to be ok, but the second one causes a recoverable crash in Interpreter, and a complete crash out of Retroarch (as per the video at the top of this thread) in the ARM32 Dynarec.  

Intepreter mode - If I put a nasty hack in the Thumb Loop in cpu.c to skip over the bl low/high instructions at 0x080A05C2 and 0x080A05C4 (using thumb_pc_offset = 4), in Interpreter mode the game will carry on into the first battle but with no picture on screen.  You can then play 'blind' to win the battle, and then the picture will return and the game will carry on as normal. 

My gut feeling is it's because there's two bl low/high instructions one after the other, but not able to pinpoint the bug as yet.

**Comment by andymcca** [comment]
Another update -

Seemingly nothing wrong with the Thumb BL instructions, having gone through and debugged and checked the resulting PC/LR values.  

Now I'm on to the instruction FOLLOWING the last bl low/high opcode, which is b580.  It _appears_ to be this instruction where everything goes to hell, so I'm comparing the handling of this opcode with the giibii Advance implementation.

**Comment by davidgfnet** [comment]
I might take a look at it later, im curious.
BTW you can use "TRACE_REGISTERS" to get a trace in dynarec mode. It's slow since it needs to save/restore regs (it was not implemented with performance in mind also), but does the trick. Also TRACE_REGISTERS exists, same as before.
Some stuff is hard to compare though (like CPSR values) since in some platforms we do not accurately calculate those (there's an optimization to skip some bit calculations if they are not used by the next instruction sort of). That means that some handlers (ie. IRQ) will push some other values to the stack in some cases, however the functional behaviour should be... identical (at least in theory).

**Comment by davidgfnet** [comment]
Ok figured out wht the issue is. It fixed a few games (see https://keen-empanada-e1c2b6.netlify.app/). It is similar to the interpreter fix I did a couple days ago :)
The current write I/O epilogue code is slightly broken in all dynarecs, but arm was more broken! On some writes DMAs can happen. If these trigger an IRQ things get messed up. Fortunately this happens very rarely (since immediately triggered DMAs do not trigger IRQs in most cases due to not being very useful). Register corruption was the culprit for ARM. However all platforms suffer from partially invalid CPSR register, which could cause further trouble. A proper fix is needed for these cases. We could separate the IRQ raise in two parts or unconditionally pack CPSR before every write. Another option could be to optimize for writes with no side effects (most of them actually).
Anyway that's a fix for later, I will hack-fix this for now since it is better than the current behaviour.
The game was out of the radar since it crashes a bit late (I usually run 150 seconds of each ROM).

Thanks for reporting this!
Also: I do not see this crashing without dynarec or on x86, did you? Im a bit puzzled :)

**Comment by andymcca** [comment]
@davidgfnet you are an absolute legend!!! 🥇 

When I saw your interpreter fix a couple of days ago I thought it might be the same/similar issue in the Dynarec.  Also a while ago I suspected the I/O Epilogue code on ARM also (you may recall I did a PR to try and rewrite that code to bring it in line with the other Dynarecs, but the changes I made didn't fix this issue).  Many times I have been convinced that I have a fix and it just hasn't worked - I am very pleased at least that I was on the right lines if just not able to execute a working fix.

The explanation makes perfect sense based on what I saw with the CPU Alerts / IRQs being raised following memory writes also.

The crash would definitely happen for me at the same point in the game in Interpreter Mode and x86 albeit in a different way - the screen would stay black and the audio would turn to garbage (like the noisy crashes that happen in other games - usually when CPU mode has been changed incorrectly, or PC corrupted).  I wonder if your commit from the other day solved it for Interpreter on this game as well?  I will try building from that commit and checking Interpreter on my platform to see if that's the case.

Again - thank you so much for the fix and explanation which has been occupying WAY too much of my thoughts and time over the past few weeks!! 😆 As a coder I can get far too overly obsessed with these things!

**Comment by davidgfnet** [comment]
No problem.
Yeah the interpreter had a very similar issue, not exactly the same bug very similar. For the x86 dynarec im not sure, didnt crash on my setup. Lemme check the code perhaps its also buggy.
However theres still the issue with thr cpsr being partially corrupted so that could indeed cause buginess. I will think of a proper fix for it and push something in a few days.

**Comment by andymcca** [comment]
OK - just to confirm, your Interpreter fix in commit c0b2f05e1d35d45ef47905c150999f88013d37ea fixes DemiKids Light in Interpreter mode on my platform!  So this will be why you're seeing it fixed now.  Definitely doesn't work before that commit.

I wonder if this commit inadvertantly fixes x86 as well?
