### ISSUE TITLE
[Top Gear Rally] Masked elements are visible

### ISSUE THREAD

**Issue by DrUm78** [libretro/gpsp#191]
Hardware:
Tested on RG350P (mips32r2) and FunKey S (armv7) handhelds.
Software:
Libretro core and standalone port.

Description:
Some layer priority issues happen in Top Gear Rally (see screenshots). Indeed, some elements (trees, signs, cars...) are visible whereas the track should hide them while they are behind.

Steps to reproduce:
1. Launch Top Gear Rally
2. Start any race
3. Notice that you see some elements through the track whereas they should be hidden

Expected behavior:
The track should always hide the elements that are behind it.

![IMG_0040](https://user-images.githubusercontent.com/46139740/115146950-1e8ca780-a059-11eb-8c6e-ca7eecf9490a.PNG) ![IMG_0042](https://user-images.githubusercontent.com/46139740/115146951-1f253e00-a059-11eb-9ab3-5186cf969edb.PNG) ![IMG_0191](https://user-images.githubusercontent.com/46139740/219872065-487726c9-7ae6-4c4e-a922-d4e81a5ee09f.PNG)

**Comment by davidgfnet** [comment]
Do you know if ReGBA has the same issue on this game? I know that console whips ReGBA as default GBA emu (IIRC). Thanks!

**Comment by DrUm78** [comment]
@davidgfnet Yep that's the same on RG350 (mips32r2) with this OPK: https://github.com/Ninoh-FOX/ReGBA

**Comment by andymcca** [comment]
Having recently reviewed the video.c code, I suspect this is the same OBJ transparency bug as is being experienced in issues #74, #207 and #210.

Transparent OBJs aren't being handled correctly be the current code.  See issue #74 for more explanation.

**Comment by andymcca** [comment]
@DrUm78 - ok, we figured this one out.  It uses the sprite cycle limit to pack the appropriate scanlines with off-screen Window OBJs so that the car (and other sprites 'invisible' due to being obscured by a hill or corner etc) are not displayed due to being above the number of sprites that can be displayed on those scan lines.

Trouble is, gpsp doesn't currently implement the sprite cycle limit 😆 

David will implement this on the ongoing video renderer rewrite (this will solve numerous other issues!), and so this will be fixed once that is merged (soon).

**Comment by davidgfnet** [comment]
Merged the new video renderer code which accounts for OBJ/Sprite rendering cycles. So this is now finally fixed.

**Comment by DrUm78** [comment]
Confirmed, it's now fixed, thanks a lot for the new renderer!
