### ISSUE TITLE
Issue: Saving the save file into proper folder.

### ISSUE THREAD

**Issue by LodanZark** [libretro/gpsp#21]
On retropie i defined the a different folder to store the save files:
savefile_directory = /home/pi/RetroPie/srm/gba/
Yet currently this emulator stores the save file in same folder as roms, and I remember in past did worked properly, maybe this issue was caused by recent commits

**Comment by fr500** [comment]
It's saving in the correct folder for me.

**Comment by LodanZark** [comment]
Weird...
I compiled 3 emulator from the source (lr-gpsp, lr-vba-next and lr-mgba), all those share the same retroarch.cfg, 2 of them save the sav\srm files on "/home/pi/RetroPie/srm/gba/" as I had defined, and meanwhile lr-gpsp saves them into "/home/pi/RetroPie/roms/gba/"
I just made a fresh compile right now and reproduce the same issue so far

**Comment by fr500** [comment]
Not sure about retropie, maybe it uses configurations per-core of something

**Comment by fr500** [comment]
Can you confirm if retropie uses configurations per-core?
Maybe by default? @joolswills knows?
That feature has a few issues, some settings do not copy over, and stuff like paths is not changed correctly because the change may be done too late, it has to be done before set_paths_redirect and that is tricky enough as it is.

**Comment by joolswills** [comment]
it doesn't use that option - we handle this ourselves by including different configs per system with a few options and which then include a main retroarch.cfg

**Comment by joolswills** [comment]
eg for gba

```
input_remapping_directory = /opt/retropie/configs/gba/

#include "/opt/retropie/configs/all/retroarch.cfg"
```

and the retroarch.cfg - http://pastebin.com/rQYAkBX5

**Comment by fr500** [comment]
That's even more obscure than configurations per-core I wouldn't know in that case.

**Comment by joolswills** [comment]
@LodanZark please post your /opt/retropie/configs/gba/retroarch.cfg config

**Comment by LodanZark** [comment]
retroarch.cfg::

input_remapping_directory = /home/pi/RetroPie/input_remapping/gba/
extraction_directory = /home/pi/RetroPie/tmp/gba/
savefile_directory = /home/pi/RetroPie/srm/gba/
savestate_directory = /home/pi/RetroPie/sstate/gba/
video_font_enable = false
#include "/opt/retropie/configs/gba/gba_video_settings.cfg"
#include "/opt/retropie/configs/all/retroarch.cfg"

gba_video_settings.cfg
video_shader = /opt/retropie/emulators/retroarch/shader/snes_lcd3x.glslp
# video_shader = /opt/retropie/emulators/retroarch/shader/shaders/lcd3x.glsl
# video_shader = /opt/retropie/emulators/retroarch/shader/shaders/dot.glsl
# video_shader = /opt/retropie/emulators/retroarch/shader/shaders/2xScaleHQ.glsl

video_shader_enable = true
video_smooth = true

aspect_ratio_index = "22"

custom_viewport_width = "501"
custom_viewport_height = "334"
custom_viewport_x = "176"
custom_viewport_y = "73"

input_overlay_enable = true
input_overlay_opacity = 1.0
input_overlay_scale = 1.0
input_overlay = /opt/retropie/configs/gba/overlay/gba1080p.cfg

**Comment by fr500** [comment]
I don't think this would have worked in the past (at least not for this particular core)

I'm not sure how #includes work in configs, but it's not gonna work for a few cores.
basically changing the dir requires to set retro_save_dir at a very specific point in the retroarch run loop and I don't know where are they applying, most likely too late.

It needs to be applied just before set_paths_redirect on most cases but a core can ask for retro_save_directory at any time so you need to make sure it doesn't change during the core execution. Since you're loading a complete config moving the place where configs are loadad could lead to some breakage so if you guys are gonna poke with this you're gonna need to be very thorough during testing. (driver changes or stuff like that in particular)

I haven't found any cores not respecting it when using my own automatic sorting feature so at least that is the correct location.

This is not core specific but it could be fixed for this particular core by using the appropriate SRAM interface instead of implementing it's own I/O for SRAM.

If either of you want to debug this in the RetroArch side, you could add a prinft or whatever in dynamic.c, look for this section

      case RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY:
         *(const char**)data = rarch_get_current_savefile_dir();
         break;

And in retroarch.c line 1423

      case RARCH_CTL_SET_PATHS_REDIRECT:
         if(settings->sort_savestates_enable || settings->sort_savefiles_enable)
         {
            if (content_ctl(CONTENT_CTL_DOES_NOT_NEED_CONTENT, NULL))
               return false;
            set_paths_redirect(global->name.base);
         }
         break;

This is very delicate code, remember that there are many codepaths that affect this that are used with less edgy cases than this so be very thorough if you make any changes to these paths.

**Comment by andymcca** [comment]
@davidgfnet having read through the above, it is established that this appears to be a RetroPie issue from several years ago.  Safe to close I think.

**Comment by andymcca** [comment]
@davidgfnet have all but confirmed this is not an issue on current version with RetroArch whilst testing the save overrides.  Saves were stored in the correct folder in the hierarchy for me (i.e. RA config folder -> Saves -> gpsp)
