### ISSUE TITLE
[vita]GoldenSun2 and RoadRash reboot after running a while

### ISSUE THREAD

**Issue by gnatydnac** [libretro/gpsp#62]
[vita]GoldenSun2 reboot to GBA.BIOS at the beginning conversation, I even tried to skip the conversation using a save created on PC but it didn't work. Same problem on Road Rash. Hope to be fixed.

**Comment by herrmartell** [comment]
To clarify, this happens after the opening story cinematic, immediately after you first see the characters in screen.

**Comment by davidgfnet** [comment]
This was indeed a known issue in the ARM dynarec. Seems it's been there since the original gpsp release (or that's what git blame claims!)
Anyway I pushed a fix for this. Please wait a couple of days and try the latest nightly (to ensure you picked up the right build with the fix in it). I tested it myself and seems to work just fine :)
